#==TRANSPARENCIAS-Y-FUENTES==#
  # Transparencias
  background_opacity 0.85
  dynamic_background_opacity yes

  # Fuentes
  font_size 11.0
  window_padding_width 6 

#==ESQUEMA-DE-COLORES==#
  # Colores Principales
  background            #161320
  foreground            #f5e0dc
  selection_background  #f5e0dc
  selection_foreground  #161320

  # Cursor
  cursor                #f5e0dc
  cursor_text_color     #161320

  # Bordes de la ventana
  active_border_color   #f9e2af
  inactive_border_color #575268
 
#==Paleta-ANSI-de-16-Colores==#
  # Negro / Gris
  color0  #1e1e2e
  color8  #575268

  # Rojo
  color1  #f38ba8
  color9  #f38ba8

  # Verde
  color2  #a6e3a1
  color10 #a6e3a1

  # Amarillo
  color3  #f9e2af
  color11 #f9e2af

  # Azul / Purpura
  color4  #89b4fa
  color12 #89b4fa

  # Magenta / Morado
  color5  #cba6f7
  color13 #cba6f7

  # Naranja / Cyan
  color6  #89dceb
  color14 #fab387

  # Blanco / Texto claro
  color7  #d9e0ee
  color15 #cdd6f4
